name: Build and Deploy
on:
  push:
    tags: ["v[0-9]+\\.[0-9]+\\.[0-9]+"]
    branches: ["development", "staging", "main"]
  workflow_dispatch:
    inputs:
      run_update_asg_only:
        description: 'Run only the update ASG process'
        required: true
        default: false
        type: boolean
      manual_ami_id:
        description: 'Manually specify AMI ID (leave empty to use default or built AMI)'
        required: false
        type: string
      use_default_ami:
        description: 'Use the default AMI'
        required: true
        default: false
        type: boolean

env:
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  HCP_PROJECT_ID: ${{ secrets.HCP_PROJECT_ID }}
  HCP_ORGANIZATION_ID: ${{ secrets.HCP_ORGANIZATION_ID }}
  HCP_BUCKET_NAME: "learn-packer-github-actions"
  SSH_PACKER: ${{ secrets.SSH_PACKER }}
  SSH_PACKER_PUB: ${{ secrets.SSH_PACKER_PUB }}
  DEFAULT_AMI_NAME: "al2023-ami-2023.4.20240528.0-kernel-6.1-x86_64"
  DEFAULT_AMI_OWNER: "659248058490"

jobs:
  build-artifact:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      version_fingerprint: ${{ steps.hcp.outputs.version_fingerprint }}
      ami_id: ${{ steps.ami.outputs.ami_id }}
    if: github.event.inputs.run_update_asg_only != 'true' && github.event.inputs.use_default_ami != 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: il-central-1 
      - name: Packer Init
        run: packer init .
      - name: Packer Build - Branches
        if: startsWith(github.ref, 'refs/heads/')
        run: |
          packer build \
            -var "SSH_PACKER=${{ secrets.SSH_PACKER }}" \
            -var "SSH_PACKER_PUB=${{ secrets.SSH_PACKER_PUB }}" \
            .
      - name: Packer Build - Tags
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          HCP_PACKER_BUILD_FINGERPRINT=$(date +'%m%d%YT%H%M%S') packer build \
            -var "SSH_PACKER=${{ secrets.SSH_PACKER }}" \
            -var "SSH_PACKER_PUB=${{ secrets.SSH_PACKER_PUB }}" \
            .
      - name: Get HCP Packer version fingerprint from Packer Manifest
        id: hcp
        run: |
          last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
          build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
          version_fingerprint=$(echo "$build" | jq -r '.custom_data.version_fingerprint')
          echo "version_fingerprint=$version_fingerprint" >> $GITHUB_OUTPUT
      - name: Get AMI ID from Packer Manifest
        id: ami
        run: |
          last_run_uuid=$(jq -r '.last_run_uuid' "./packer_manifest.json")
          build=$(jq -r '.builds[] | select(.packer_run_uuid == "'"$last_run_uuid"'")' "./packer_manifest.json")
          ami_id=$(echo "$build" | jq -r '.artifact_id' | cut -d':' -f2)
          echo "ami_id=$ami_id" >> $GITHUB_OUTPUT
          echo "AMI ID from Packer build: $ami_id"

  update-hcp-packer-channel:
    name: Update HCP Packer channel
    needs: build-artifact
    runs-on: ubuntu-latest
    if: github.event.inputs.run_update_asg_only != 'true' && github.event.inputs.use_default_ami != 'true'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Create and set channel
        working-directory: .github/scripts
        run: |
          channel_name=$(echo "${{ github.ref_name }}" | sed 's/\\./-/g')
          ./create_channel_version.sh "$HCP_BUCKET_NAME" "$channel_name" "${{ needs.build-artifact.outputs.version_fingerprint }}"


  update-asg:
    name: Update Frontend Auto Scaling Group
    needs: build-artifact
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: il-central-1
      - name: Determine AMI ID
        id: get_ami
        run: |
          if [ "${{ github.event.inputs.use_default_ami }}" == "true" ]; then
            AMI_ID=$(aws ec2 describe-images \
              --owners ${{ env.DEFAULT_AMI_OWNER }} \
              --filters "Name=name,Values=${{ env.DEFAULT_AMI_NAME }}" \
              --query 'Images[0].ImageId' \
              --output text)
          elif [ -n "${{ github.event.inputs.manual_ami_id }}" ]; then
            AMI_ID=${{ github.event.inputs.manual_ami_id }}
          elif [ "${{ github.event.inputs.run_update_asg_only }}" == "true" ]; then
            echo "Error: When running update ASG only, you must specify a manual AMI ID or use the default AMI."
            exit 1
          else
            AMI_ID=${{ needs.build-artifact.outputs.ami_id }}
          fi
          echo "ami_id=$AMI_ID" >> $GITHUB_OUTPUT
      - name: Update and Refresh ASG
        env:
          FRONTEND_ASG_NAME: scaling-group-dev-frontend
          LAUNCH_TEMPLATE_NAME: template-for-heshbonaitplus-frontend
        run: |
          chmod +x .github/scripts/Updated\ update_asg.sh
          .github/scripts/Updated\ update_asg.sh "${{ steps.get_ami.outputs.ami_id }}" "$FRONTEND_ASG_NAME" "$LAUNCH_TEMPLATE_NAME"
